#ifndef CATWHISPER_VERSION_HPP
#define CATWHISPER_VERSION_HPP

#define CATWHISPER_VERSION_MAJOR 0
#define CATWHISPER_VERSION_MINOR 1
#define CATWHISPER_VERSION_PATCH 0

#define CATWHISPER_VERSION \
    ((CATWHISPER_VERSION_MAJOR << 20) | \
     (CATWHISPER_VERSION_MINOR << 10) | \
     (CATWHISPER_VERSION_PATCH))

#endif // CATWHISPER_VERSION_HPP
